# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SteerUp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SteerUp

pod 'Firebase/Analytics'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'GoogleSignIn'
end
